/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-canvas': 'var(--bg-canvas)',
        'bg-canvas-inset': 'var(--bg-canvas-inset)',
        'surface-card': 'var(--surface-card)',
        'surface-raised': 'var(--surface-raised)',
        'surface-overlay': 'var(--surface-overlay)',

        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-on-accent': 'var(--text-on-accent)',
        'text-inverse': 'var(--text-inverse)',

        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'border-focus': 'var(--border-focus)',

        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-pressed': 'var(--accent-pressed)',
        'accent-tint': 'var(--accent-tint)',

        'focus-ring': 'var(--focus-ring)',

        'paper-0': 'var(--paper-0)',
        'paper-1': 'var(--paper-1)',
        'paper-2': 'var(--paper-2)',
        'paper-3': 'var(--paper-3)',

        'ink-900': 'var(--ink-900)',
        'ink-700': 'var(--ink-700)',
        'ink-500': 'var(--ink-500)',
        'ink-400': 'var(--ink-400)',
        'ink-300': 'var(--ink-300)',
        line: 'var(--line)',
        'line-strong': 'var(--line-strong)',

        'flush-50': 'var(--flush-50)',
        'flush-100': 'var(--flush-100)',
        'flush-300': 'var(--flush-300)',
        'flush-500': 'var(--flush-500)',
        'flush-600': 'var(--flush-600)',
        'flush-700': 'var(--flush-700)',

        'mood-lavender': 'var(--mood-lavender)',
        'mood-lavender-ink': 'var(--mood-lavender-ink)',
        'mood-mint': 'var(--mood-mint)',
        'mood-mint-ink': 'var(--mood-mint-ink)',
        'mood-cream': 'var(--mood-cream)',
        'mood-cream-ink': 'var(--mood-cream-ink)',
        'mood-terracotta': 'var(--mood-terracotta)',
        'mood-terracotta-ink': 'var(--mood-terracotta-ink)',
        'mood-sky': 'var(--mood-sky)',
        'mood-sky-ink': 'var(--mood-sky-ink)',
        'mood-blush': 'var(--mood-blush)',
        'mood-blush-ink': 'var(--mood-blush-ink)',

        'success-500': 'var(--success-500)',
        'success-tint': 'var(--success-tint)',
        'warning-500': 'var(--warning-500)',
        'warning-tint': 'var(--warning-tint)',
        'danger-500': 'var(--danger-500)',
        'danger-tint': 'var(--danger-tint)',
        'info-500': 'var(--info-500)',
        'info-tint': 'var(--info-tint)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        'display-xl': 'var(--text-display-xl)',
        'display-l': 'var(--text-display-l)',
        'display-m': 'var(--text-display-m)',
        'display-s': 'var(--text-display-s)',
        xl: 'var(--text-xl)',
        lg: 'var(--text-lg)',
        md: 'var(--text-md)',
        sm: 'var(--text-sm)',
        xs: 'var(--text-xs)',
        '2xs': 'var(--text-2xs)',
      },
      lineHeight: {
        tight: 'var(--lh-tight)',
        snug: 'var(--lh-snug)',
        normal: 'var(--lh-normal)',
        relaxed: 'var(--lh-relaxed)',
      },
      letterSpacing: {
        tight: 'var(--ls-tight)',
        normal: 'var(--ls-normal)',
        wide: 'var(--ls-wide)',
        eyebrow: 'var(--ls-eyebrow)',
      },
      fontWeight: {
        light: 'var(--fw-light)',
        regular: 'var(--fw-regular)',
        medium: 'var(--fw-medium)',
        semibold: 'var(--fw-semibold)',
        bold: 'var(--fw-bold)',
        extrabold: 'var(--fw-extrabold)',
      },
    },
  },
  plugins: [],
};
